version: '2'
services:
    teste-app:
        image: teste
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://teste-mariadb:3306/teste
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    teste-mariadb:
        extends:
            file: mariadb.yml
            service: teste-mariadb
